1: compile
	cc -c calnum1.c
	cc -o test calnum1.o test.o -lm
	rm -rf calnum1.o test.o
2: compile
	cc -c calnum2.c
	cc -o test calnum2.o test.o -lm
	rm -rf calnum2.o test.o
3: compile
	cc -c calnum3.c
	cc -o test calnum3.o test.o -lm
	rm -rf calnum3.o test.o

compile:
	cc -c test.c -lm