general: compile
	cc -c calnum.c
	cc -o main calnum.o main.o -lm

1: compile
	cc -c calnum1.c
	cc -o main calnum1.o main.o -lm
2: compile
	cc -c calnum2.c
	cc -o main calnum2.o main.o -lm
3: compile
	cc -c calnum3.c
	cc -o main calnum3.o main.o -lm

compile:
	cc -c main.c -lm
